# Generated by Django 5.1.4 on 2025-01-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_exam_delete_checked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exam',
        ),
    ]
